### ISSUE TITLE
ValueError: operands could not be broadcast together

### ISSUE THREAD

**Issue by swemeshy** [slowkow/harmonypy#12]
Hi Kamil,

I get the following error when I run harmonization on an AnnData with ~2.7k cells, using a PCA matrix of 18 PCs and using one variable for `vars_use`, which has 30 unique values:
```
Traceback (most recent call last):
  File "/home/sramesh/software/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-f125ff7d55f1>", line 1, in <module>
    hm_obj = hm.run_harmony(adata.obsm['X_pca'], adata.obs, [channel_name])
  File "/home/sramesh/software/miniconda3/lib/python3.8/site-packages/harmonypy/harmony.py", line 124, in run_harmony
    ho = Harmony(
  File "/home/sramesh/software/miniconda3/lib/python3.8/site-packages/harmonypy/harmony.py", line 172, in __init__
    self.init_cluster()
  File "/home/sramesh/software/miniconda3/lib/python3.8/site-packages/harmonypy/harmony.py", line 202, in init_cluster
    self.compute_objective()
  File "/home/sramesh/software/miniconda3/lib/python3.8/site-packages/harmonypy/harmony.py", line 214, in compute_objective
    w = np.dot(y * z, self.Phi)
ValueError: operands could not be broadcast together with shapes (92,30) (92,35)
```

Not sure why I'm getting this error, when usually harmonypy works most of the time. Any help is appreciated. Thanks!

**Comment by slowkow** [comment]
I was able to reproduce your error.

If we look at the `assignment` column, we can see the issue is the presence of 5 unused categories:

```
[ins] In [8]: adata.obs['assignment'].value_counts().shape
Out[8]: (35,)

[ins] In [9]: (adata.obs['assignment'].value_counts() > 0).sum()
Out[9]: 30
```

We can use `remove_unused_categories()` to resolve the issue:

```
[ins] In [10]: adata.obs['assignment'].cat.remove_unused_categories(inplace = True)

[ins] In [11]: hm_obj = hm.run_harmony(adata.obsm['X_pca'], adata.obs, ['assignment'])
2021-05-17 10:41:38,184 - harmonypy - INFO - Iteration 1 of 10
2021-05-17 10:41:39,243 - harmonypy - INFO - Iteration 2 of 10
2021-05-17 10:41:40,278 - harmonypy - INFO - Converged after 2 iterations
```
